version: '3.9'

services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
      - ARANGO_PORT=8530
      - ARANGO_URL=172.16.231.99
      - ARANGO_USER=${ARANGO_USER}
    volumes:
      - ./backend:/app/
    networks:
      backend:
        ipv4_address: 172.16.231.100
    ports:
      - 8000:8000
    restart: on-failure

networks:
  backend:
    name: project_hub_backend_network
    ipam:
      driver: default
      config:
        - subnet: 172.16.231.0/24
          gateway: 172.16.231.1
